### PR TITLE
Import; Export; new UI; new Icon; Android Marshmallow Support

### PR DESCRIPTION
**Pull request by UnknownUntilNow**
Import and export was requested at https://github.com/n76/wifi_backend/issues/17

### CODE REVIEW

**Comment by n76** [comment]
Issues:
1. Database from earlier version was lost when I upgraded. Not yet investigated reason.

2. Logic to increase radius (decrease accuracy) when no WiFi APs are detected is not working (or missing as I haven't looked for it yet).

3. Export fails leaving a zero length file. Logcat shows:

    V/WindowManager( 1254): not Base app: Adding window Window{3401d755 u0 org.fitchfamily.android.wifi_backend/org.fitchfamily.android.wifi_backend.ui.MainActivity_} at 9 of 16
    D//RequestProcessor.java:63( 8707): 13:04:48.767 SpiceManagerThread 0 Adding request to queue 975482676: CachedSpiceRequest [requestCacheKey=ExportSpiceRequest, cacheDuration=-1, spiceRequest=org.fitchfamily.android.wifi_backend.data.ExportSpiceRequest@2538a15d] size is 0
    D//RequestProcessor.java:85( 8707): 13:04:48.773 SpiceManagerThread 0 Adding entry for type class org.fitchfamily.android.wifi_backend.data.ExportSpiceRequest$Result and cacheKey ExportSpiceRequest.
    D//SpiceServiceListenerNotifier.java:175( 8707): 13:04:48.814 main Processing request added: CachedSpiceRequest [requestCacheKey=ExportSpiceRequest, cacheDuration=-1, spiceRequest=org.fitchfamily.android.wifi_backend.data.ExportSpiceRequest@2538a15d]
    D//DefaultRequestRunner.java:83( 8707): 13:04:48.828 Thread-14349 Processing request : CachedSpiceRequest [requestCacheKey=ExportSpiceRequest, cacheDuration=-1, spiceRequest=org.fitchfamily.android.wifi_backend.data.ExportSpiceRequest@2538a15d]
    E//DefaultRequestRunner.java:154( 8707):    at org.fitchfamily.android.wifi_backend.data.ExportSpiceRequest.loadDataFromNetwork(ExportSpiceRequest.java:77)
    E//DefaultRequestRunner.java:154( 8707):    at org.fitchfamily.android.wifi_backend.data.ExportSpiceRequest.loadDataFromNetwork(ExportSpiceRequest.java:36)
    D//DefaultRequestRunner.java:295( 8707): 13:04:48.949 Thread-14349 It tooks 156 ms to process request CachedSpiceRequest [requestCacheKey=ExportSpiceRequest, cacheDuration=-1, spiceRequest=org.fitchfamily.android.wifi_backend.data.ExportSpiceRequest@2538a15d].
    V/NlpLocationBackendFuser(11554): location=Location[network 33.425949,-117.611389 acc=1165 et=+6d4h19m1s441ms {Bundle[{noGPSLocation=Location[network 33.425949,-117.611389 acc=1165 et=+6d4h19m1s441ms {Bundle[{AVERAGED_OF=1, SERVICE_BACKEND_PROVIDER=gsm, SERVICE_BACKEND_COMPONENT=org.fitchfamily.android.gsmlocation/.GsmService}]}], AVERAGED_OF=1, SERVICE_BACKEND_PROVIDER=gsm, SERVICE_BACKEND_COMPONENT=org.fitchfamily.android.gsmlocation/.GsmService, OTHER_BACKEND_RESULTS=[Location[network 33.423507,-117.614456 acc=39 et=+6d3h59m13s944ms {Bundle[{noGPSLocation=Location[network 33.423507,-117.614456 acc=39 et=+6d3h59m13s944ms {Bundle[{AVERAGED_OF=10, SERVICE_BACKEND_PROVIDER=wifi, SERVICE_BACKEND_COMPONENT=org.fitchfamily.android.wifi_backend/.backend.BackendService_}]}], AVERAGED_OF=10, SERVICE_BACKEND_PROVIDER=wifi, SERVICE_BACKEND_COMPONENT=org.fitchfamily.android.wifi_backend/.backend.BackendService_}]}]]}]}]
    D//DefaultRequestRunner.java:83( 8707): 13:04:51.487 Thread-14349 Processing request : CachedSpiceRequest [requestCacheKey=ExportSpiceRequest, cacheDuration=-1, spiceRequest=org.fitchfamily.android.wifi_backend.data.ExportSpiceRequest@2538a15d]
    E//DefaultRequestRunner.java:154( 8707):    at org.fitchfamily.android.wifi_backend.data.ExportSpiceRequest.loadDataFromNetwork(ExportSpiceRequest.java:77)
    E//DefaultRequestRunner.java:154( 8707):    at org.fitchfamily.android.wifi_backend.data.ExportSpiceRequest.loadDataFromNetwork(ExportSpiceRequest.java:36)
    D//DefaultRequestRunner.java:295( 8707): 13:04:51.555 Thread-14349 It tooks 64 ms to process request CachedSpiceRequest [requestCacheKey=ExportSpiceRequest, cacheDuration=-1, spiceRequest=org.fitchfamily.android.wifi_backend.data.ExportSpiceRequest@2538a15d].
    D//DefaultRequestRunner.java:83( 8707): 13:04:54.094 Thread-14349 Processing request : CachedSpiceRequest [requestCacheKey=ExportSpiceRequest, cacheDuration=-1, spiceRequest=org.fitchfamily.android.wifi_backend.data.ExportSpiceRequest@2538a15d]
    E//DefaultRequestRunner.java:154( 8707):    at org.fitchfamily.android.wifi_backend.data.ExportSpiceRequest.loadDataFromNetwork(ExportSpiceRequest.java:77)
    E//DefaultRequestRunner.java:154( 8707):    at org.fitchfamily.android.wifi_backend.data.ExportSpiceRequest.loadDataFromNetwork(ExportSpiceRequest.java:36)
    V//RequestProgressManager.java:161( 8707): 13:04:54.171 Thread-14349 Removing CachedSpiceRequest [requestCacheKey=ExportSpiceRequest, cacheDuration=-1, spiceRequest=org.fitchfamily.android.wifi_backend.data.ExportSpiceRequest@2538a15d]  size is 1
    D//DefaultRequestRunner.java:295( 8707): 13:04:54.175 Thread-14349 It tooks 81 ms to process request CachedSpiceRequest [requestCacheKey=ExportSpiceRequest, cacheDuration=-1, spiceRequest=org.fitchfamily.android.wifi_backend.data.ExportSpiceRequest@2538a15d].

You are using some libraries I am not familiar with so it will take me a while to sort through.

**Comment by UnknownUntilNow** [comment]
The logic to increase the radius was not changed and is at <https://github.com/n76/wifi_backend/pull/19/files#diff-965f019b00f961d40b23f6fcdcb9ceb2R226>.
It is called with null from <https://github.com/n76/wifi_backend/pull/19/files#diff-965f019b00f961d40b23f6fcdcb9ceb2R141> if it wasn't possible to resolve the location.

I tried exporting at two different phones and it worked there. An exception will look like this at the logcat (with red font in Android Studio):

        An exception occurred during request network execution :null
            java.io.IOException
            at org.fitchfamily.android.wifi_backend.data.ExportSpiceRequest.loadDataFromNetwork(ExportSpiceRequest.java:57)
            at org.fitchfamily.android.wifi_backend.data.ExportSpiceRequest.loadDataFromNetwork(ExportSpiceRequest.java:36)
            at com.octo.android.robospice.request.CachedSpiceRequest.loadDataFromNetwork(CachedSpiceRequest.java:48)
            at com.octo.android.robospice.request.DefaultRequestRunner.processRequest(DefaultRequestRunner.java:150)
            at com.octo.android.robospice.request.DefaultRequestRunner$1.run(DefaultRequestRunner.java:217)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:848)

**Comment by UnknownUntilNow** [comment]
This PR fixed <https://github.com/n76/wifi_backend/issues/17> (it is not yet closed).

**Comment by n76** [comment]
With the fix for moving the old database I know show over 128000 APs. When trying to export them the file ended up with only 1024 entries and a number of exceptions in the logcat as shown below. My phone is an older one Samsung/Google Galaxy Nexus (maguro) with limited memory and that might be contributing to the problem.

    V/WindowManager( 1254): not Base app: Adding window Window{33729c2a u0 org.fitchfamily.android.wifi_backend/org.fitchfamily.android.wifi_backend.ui.MainActivity_} at 9 of 16
    V//SpiceManager.java:1191(16131): 23:56:39.383 SpiceManagerThread 0 Binding to service.
    V//SpiceManager.java:1197(16131): 23:56:39.389 SpiceManagerThread 0 Binding to service succeeded.
    D//SpiceManager.java:1245(16131): 23:56:39.389 SpiceManagerThread 0 Waiting for service to be bound.
    D//SpiceManager.java:212(16131): 23:56:39.391 main SpiceManager started.
    D//SpiceManager.java:489(16131): 23:56:39.396 main adding request to request queue
    D//SpiceService.java:134(16131): 23:56:39.544 main SpiceService instance created.
    V//SpiceService.java:506(16131): 23:56:39.549 main Pending requests : 0
    V//SpiceService.java:508(16131): 23:56:39.551 main Stop foreground
    D//SpiceServiceListenerNotifier.java:33(16131): 23:56:39.611 main Message Queue starting
    D//SpiceManager.java:1088(16131): 23:56:39.612 main Bound to service : SpiceService
    D//SpiceManager.java:1252(16131): 23:56:39.613 SpiceManagerThread 0 Bound ok.
    D//SpiceManager.java:286(16131): 23:56:39.613 SpiceManagerThread 0 Sending request to service : CachedSpiceRequest
    D//RequestProcessor.java:63(16131): 23:56:39.614 SpiceManagerThread 0 Adding request to queue 669944250: CachedSpiceRequest [requestCacheKey=ExportSpiceRequest, cacheDuration=-1, spiceRequest=org.fitchfamily.android.wifi_backend.data.ExportSpiceRequest@2e63806b] size is 0
    D//RequestProcessor.java:85(16131): 23:56:39.616 SpiceManagerThread 0 Adding entry for type class org.fitchfamily.android.wifi_backend.data.ExportSpiceRequest$Result and cacheKey ExportSpiceRequest.
    D//RequestProgressManager.java:61(16131): 23:56:39.623 SpiceManagerThread 0 Request was added to queue.
    D//SpiceServiceListenerNotifier.java:146(16131): 23:56:39.630 SpiceManagerThread 0 Message queue is Handler (android.os.Handler) {fa22061}
    D//RequestProgressManager.java:82(16131): 23:56:39.633 SpiceManagerThread 0 Sending progress PENDING
    D//SpiceServiceListenerNotifier.java:146(16131): 23:56:39.636 SpiceManagerThread 0 Message queue is Handler (android.os.Handler) {fa22061}
    D//SpiceServiceListenerNotifier.java:175(16131): 23:56:39.646 main Processing request added: CachedSpiceRequest [requestCacheKey=ExportSpiceRequest, cacheDuration=-1, spiceRequest=org.fitchfamily.android.wifi_backend.data.ExportSpiceRequest@2e63806b]
    V//DefaultRequestListenerNotifier.java:131(16131): 23:56:39.647 main Notifying 1 listeners of progress com.octo.android.robospice.request.listener.RequestProgress@39eb8786
    V//SpiceService.java:506(16131): 23:56:39.661 SpiceManagerThread 0 Pending requests : 1
    V//SpiceService.java:508(16131): 23:56:39.662 SpiceManagerThread 0 Stop foreground
    D//DefaultRequestRunner.java:83(16131): 23:56:39.664 Thread-16983 Processing request : CachedSpiceRequest [requestCacheKey=ExportSpiceRequest, cacheDuration=-1, spiceRequest=org.fitchfamily.android.wifi_backend.data.ExportSpiceRequest@2e63806b]
    D//DefaultRequestRunner.java:129(16131): 23:56:39.665 Thread-16983 Cache content not available or expired or disabled
    D//DefaultRequestRunner.java:148(16131): 23:56:39.666 Thread-16983 Calling netwok request.
    D//RequestProgressManager.java:82(16131): 23:56:39.666 Thread-16983 Sending progress LOADING_FROM_NETWORK
    D//SpiceServiceListenerNotifier.java:146(16131): 23:56:39.667 Thread-16983 Message queue is Handler (android.os.Handler) {fa22061}
    V//DefaultRequestListenerNotifier.java:131(16131): 23:56:39.670 main Notifying 1 listeners of progress com.octo.android.robospice.request.listener.RequestProgress@13c94874
    D/Documents(16292): userMode=0, userSortOrder=0 --> mode=1, sortOrder=2
    W/CursorWindow(16131): Window is full: requested allocation 12 bytes, free space 11 bytes, window size 2097152 bytes
    E//DefaultRequestRunner.java:154(16131): 23:56:43.539 Thread-16983 An exception occurred during request network execution :Nesting problem.
    E//DefaultRequestRunner.java:154(16131): java.lang.IllegalStateException: Nesting problem.
    E//DefaultRequestRunner.java:154(16131): 	at com.google.gson.stream.JsonWriter.close(JsonWriter.java:339)
    E//DefaultRequestRunner.java:154(16131): 	at com.google.gson.stream.JsonWriter.endArray(JsonWriter.java:297)
    E//DefaultRequestRunner.java:154(16131): 	at org.fitchfamily.android.wifi_backend.data.ExportSpiceRequest.loadDataFromNetwork(ExportSpiceRequest.java:77)
    E//DefaultRequestRunner.java:154(16131): 	at org.fitchfamily.android.wifi_backend.data.ExportSpiceRequest.loadDataFromNetwork(ExportSpiceRequest.java:36)
    E//DefaultRequestRunner.java:154(16131): 	at com.octo.android.robospice.request.CachedSpiceRequest.loadDataFromNetwork(CachedSpiceRequest.java:48)
    E//DefaultRequestRunner.java:154(16131): 	at com.octo.android.robospice.request.DefaultRequestRunner.processRequest(DefaultRequestRunner.java:150)
    E//DefaultRequestRunner.java:154(16131): 	at com.octo.android.robospice.request.DefaultRequestRunner$1.run(DefaultRequestRunner.java:217)
    E//DefaultRequestRunner.java:154(16131): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
    E//DefaultRequestRunner.java:154(16131): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    E//DefaultRequestRunner.java:154(16131): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    E//DefaultRequestRunner.java:154(16131): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    E//DefaultRequestRunner.java:154(16131): 	at java.lang.Thread.run(Thread.java:818)
    D//DefaultRequestRunner.java:295(16131): 23:56:43.544 Thread-16983 It tooks 3881 ms to process request CachedSpiceRequest [requestCacheKey=ExportSpiceRequest, cacheDuration=-1, spiceRequest=org.fitchfamily.android.wifi_backend.data.ExportSpiceRequest@2e63806b].
    D/MediaScannerReceiver(12849): action: android.intent.action.MEDIA_SCANNER_SCAN_FILE path: /storage/emulated/0/Download/wifi.json (1)
    D//DefaultRequestRunner.java:83(16131): 23:56:46.088 Thread-16983 Processing request : CachedSpiceRequest [requestCacheKey=ExportSpiceRequest, cacheDuration=-1, spiceRequest=org.fitchfamily.android.wifi_backend.data.ExportSpiceRequest@2e63806b]
    D//DefaultRequestRunner.java:129(16131): 23:56:46.090 Thread-16983 Cache content not available or expired or disabled
    D//DefaultRequestRunner.java:148(16131): 23:56:46.092 Thread-16983 Calling netwok request.
    D//RequestProgressManager.java:82(16131): 23:56:46.094 Thread-16983 Sending progress LOADING_FROM_NETWORK
    D//SpiceServiceListenerNotifier.java:146(16131): 23:56:46.096 Thread-16983 Message queue is Handler (android.os.Handler) {fa22061}
    V//DefaultRequestListenerNotifier.java:131(16131): 23:56:46.118 main Notifying 1 listeners of progress com.octo.android.robospice.request.listener.RequestProgress@8689612
    W/CursorWindow(16131): Window is full: requested allocation 12 bytes, free space 11 bytes, window size 2097152 bytes
    D/ConnectivityService( 1254): updateNetworkScore for NetworkAgentInfo [WIFI () - 140] to 52
    D/ConnectivityService( 1254): rematching NetworkAgentInfo [WIFI () - 140]
    D/ConnectivityService( 1254): Network NetworkAgentInfo [WIFI () - 140] was already satisfying request 1. No change.
    D/ConnectivityService( 1254): notifyType AVAILABLE for NetworkAgentInfo [WIFI () - 140]
    D/ConnectivityManager.CallbackHandler( 1378): CM callback handler got msg 524290
    I/art     (16131): Background sticky concurrent mark sweep GC freed 126584(4MB) AllocSpace objects, 0(0B) LOS objects, 29% free, 11MB/16MB, paused 13.275ms total 78.063ms
    E//DefaultRequestRunner.java:154(16131): 23:56:49.408 Thread-16983 An exception occurred during request network execution :Nesting problem.
    E//DefaultRequestRunner.java:154(16131): java.lang.IllegalStateException: Nesting problem.
    E//DefaultRequestRunner.java:154(16131): 	at com.google.gson.stream.JsonWriter.close(JsonWriter.java:339)
    E//DefaultRequestRunner.java:154(16131): 	at com.google.gson.stream.JsonWriter.endArray(JsonWriter.java:297)
    E//DefaultRequestRunner.java:154(16131): 	at org.fitchfamily.android.wifi_backend.data.ExportSpiceRequest.loadDataFromNetwork(ExportSpiceRequest.java:77)
    E//DefaultRequestRunner.java:154(16131): 	at org.fitchfamily.android.wifi_backend.data.ExportSpiceRequest.loadDataFromNetwork(ExportSpiceRequest.java:36)
    E//DefaultRequestRunner.java:154(16131): 	at com.octo.android.robospice.request.CachedSpiceRequest.loadDataFromNetwork(CachedSpiceRequest.java:48)
    E//DefaultRequestRunner.java:154(16131): 	at com.octo.android.robospice.request.DefaultRequestRunner.processRequest(DefaultRequestRunner.java:150)
    E//DefaultRequestRunner.java:154(16131): 	at com.octo.android.robospice.request.DefaultRequestRunner$1.run(DefaultRequestRunner.java:217)
    E//DefaultRequestRunner.java:154(16131): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
    E//DefaultRequestRunner.java:154(16131): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    E//DefaultRequestRunner.java:154(16131): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    E//DefaultRequestRunner.java:154(16131): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    E//DefaultRequestRunner.java:154(16131): 	at java.lang.Thread.run(Thread.java:818)
    D//DefaultRequestRunner.java:295(16131): 23:56:49.410 Thread-16983 It tooks 3323 ms to process request CachedSpiceRequest [requestCacheKey=ExportSpiceRequest, cacheDuration=-1, spiceRequest=org.fitchfamily.android.wifi_backend.data.ExportSpiceRequest@2e63806b].
    D/MediaScannerReceiver(12849): action: android.intent.action.MEDIA_SCANNER_SCAN_FILE path: /storage/emulated/0/Download/wifi.json (1)
    D/ConnectivityService( 1254): updateNetworkScore for NetworkAgentInfo [WIFI () - 140] to 51
    D/ConnectivityService( 1254): rematching NetworkAgentInfo [WIFI () - 140]
    D/ConnectivityService( 1254): Network NetworkAgentInfo [WIFI () - 140] was already satisfying request 1. No change.
    D/ConnectivityService( 1254): notifyType AVAILABLE for NetworkAgentInfo [WIFI () - 140]
    D/ConnectivityManager.CallbackHandler( 1378): CM callback handler got msg 524290
    D//DefaultRequestRunner.java:83(16131): 23:56:51.957 Thread-16983 Processing request : CachedSpiceRequest [requestCacheKey=ExportSpiceRequest, cacheDuration=-1, spiceRequest=org.fitchfamily.android.wifi_backend.data.ExportSpiceRequest@2e63806b]
    D//DefaultRequestRunner.java:129(16131): 23:56:51.959 Thread-16983 Cache content not available or expired or disabled
    D//DefaultRequestRunner.java:148(16131): 23:56:51.967 Thread-16983 Calling netwok request.
    D//RequestProgressManager.java:82(16131): 23:56:51.980 Thread-16983 Sending progress LOADING_FROM_NETWORK
    D//SpiceServiceListenerNotifier.java:146(16131): 23:56:51.982 Thread-16983 Message queue is Handler (android.os.Handler) {fa22061}
    V//DefaultRequestListenerNotifier.java:131(16131): 23:56:52.002 main Notifying 1 listeners of progress com.octo.android.robospice.request.listener.RequestProgress@162d91e3
    W/CursorWindow(16131): Window is full: requested allocation 12 bytes, free space 11 bytes, window size 2097152 bytes
    E//DefaultRequestRunner.java:154(16131): 23:56:55.628 Thread-16983 An exception occurred during request network execution :Nesting problem.
    E//DefaultRequestRunner.java:154(16131): java.lang.IllegalStateException: Nesting problem.
    E//DefaultRequestRunner.java:154(16131): 	at com.google.gson.stream.JsonWriter.close(JsonWriter.java:339)
    E//DefaultRequestRunner.java:154(16131): 	at com.google.gson.stream.JsonWriter.endArray(JsonWriter.java:297)
    E//DefaultRequestRunner.java:154(16131): 	at org.fitchfamily.android.wifi_backend.data.ExportSpiceRequest.loadDataFromNetwork(ExportSpiceRequest.java:77)
    E//DefaultRequestRunner.java:154(16131): 	at org.fitchfamily.android.wifi_backend.data.ExportSpiceRequest.loadDataFromNetwork(ExportSpiceRequest.java:36)
    E//DefaultRequestRunner.java:154(16131): 	at com.octo.android.robospice.request.CachedSpiceRequest.loadDataFromNetwork(CachedSpiceRequest.java:48)
    E//DefaultRequestRunner.java:154(16131): 	at com.octo.android.robospice.request.DefaultRequestRunner.processRequest(DefaultRequestRunner.java:150)
    E//DefaultRequestRunner.java:154(16131): 	at com.octo.android.robospice.request.DefaultRequestRunner$1.run(DefaultRequestRunner.java:217)
    E//DefaultRequestRunner.java:154(16131): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
    E//DefaultRequestRunner.java:154(16131): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    E//DefaultRequestRunner.java:154(16131): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    E//DefaultRequestRunner.java:154(16131): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    E//DefaultRequestRunner.java:154(16131): 	at java.lang.Thread.run(Thread.java:818)
    D//RequestProgressManager.java:82(16131): 23:56:55.629 Thread-16983 Sending progress COMPLETE
    D//SpiceServiceListenerNotifier.java:146(16131): 23:56:55.629 Thread-16983 Message queue is Handler (android.os.Handler) {fa22061}
    D//SpiceServiceListenerNotifier.java:146(16131): 23:56:55.633 Thread-16983 Message queue is Handler (android.os.Handler) {fa22061}
    V//RequestProgressManager.java:161(16131): 23:56:55.634 Thread-16983 Removing CachedSpiceRequest [requestCacheKey=ExportSpiceRequest, cacheDuration=-1, spiceRequest=org.fitchfamily.android.wifi_backend.data.ExportSpiceRequest@2e63806b]  size is 1
    D//RequestProgressManager.java:91(16131): 23:56:55.639 Thread-16983 Sending all request complete.
    V//SpiceService.java:495(16131): 23:56:55.642 Thread-16983 Pending requests : 0
    D//SpiceServiceListenerNotifier.java:146(16131): 23:56:55.642 Thread-16983 Message queue is Handler (android.os.Handler) {fa22061}
    D//DefaultRequestRunner.java:295(16131): 23:56:55.643 Thread-16983 It tooks 3687 ms to process request CachedSpiceRequest [requestCacheKey=ExportSpiceRequest, cacheDuration=-1, spiceRequest=org.fitchfamily.android.wifi_backend.data.ExportSpiceRequest@2e63806b].
    V//DefaultRequestListenerNotifier.java:131(16131): 23:56:55.652 main Notifying 1 listeners of progress com.octo.android.robospice.request.listener.RequestProgress@c6c77e0
    V//DefaultRequestListenerNotifier.java:166(16131): 23:56:55.653 main Notifying 1 listeners of request failure
    V//DefaultRequestListenerNotifier.java:172(16131): 23:56:55.653 main Notifying ExportProgressDialog_

**Pull request merged**
