### PR TITLE
Add Serbian translation

### PR DESCRIPTION
**Pull request by pejakm**

### CODE REVIEW

**Comment by pejakm** [comment]
Thanks! :)

**Comment by n76** [comment]
I will be pushing a new version within the next few days which will change the text strings slightly. I will let you know when I do so that you can review your translation.

Thank you for adding the translation!

**Comment by pejakm** [comment]
No problem, I will monitor the project. If you have a paypal, I would like to buy you a beer (at least I can do that). :) Your projects are very useful to me. :)

**Comment by n76** [comment]
I do have PayPal. . . But I've been using open source software for years and feel my effort here is paying back my debts to the cause. The fact that you and others find it useful is payback enough for me.

**Comment by pejakm** [comment]
Thank you very much once again. :)

**Pull request merged**
